#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association_VVA.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RESERVATION")]
	public partial class ReservationDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void InsertCOMPTE(COMPTE instance);
    partial void UpdateCOMPTE(COMPTE instance);
    partial void DeleteCOMPTE(COMPTE instance);
    partial void InsertETAT_RESA(ETAT_RESA instance);
    partial void UpdateETAT_RESA(ETAT_RESA instance);
    partial void DeleteETAT_RESA(ETAT_RESA instance);
    partial void InsertHEBERGEMENT(HEBERGEMENT instance);
    partial void UpdateHEBERGEMENT(HEBERGEMENT instance);
    partial void DeleteHEBERGEMENT(HEBERGEMENT instance);
    partial void InsertRESA(RESA instance);
    partial void UpdateRESA(RESA instance);
    partial void DeleteRESA(RESA instance);
    partial void InsertSEMAINE(SEMAINE instance);
    partial void UpdateSEMAINE(SEMAINE instance);
    partial void DeleteSEMAINE(SEMAINE instance);
    partial void InsertTYPE_HEB(TYPE_HEB instance);
    partial void UpdateTYPE_HEB(TYPE_HEB instance);
    partial void DeleteTYPE_HEB(TYPE_HEB instance);
    #endregion
		
		public ReservationDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["RESERVATIONConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ReservationDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReservationDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReservationDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReservationDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<COMPTE> COMPTE
		{
			get
			{
				return this.GetTable<COMPTE>();
			}
		}
		
		public System.Data.Linq.Table<ETAT_RESA> ETAT_RESA
		{
			get
			{
				return this.GetTable<ETAT_RESA>();
			}
		}
		
		public System.Data.Linq.Table<HEBERGEMENT> HEBERGEMENT
		{
			get
			{
				return this.GetTable<HEBERGEMENT>();
			}
		}
		
		public System.Data.Linq.Table<RESA> RESA
		{
			get
			{
				return this.GetTable<RESA>();
			}
		}
		
		public System.Data.Linq.Table<SEMAINE> SEMAINE
		{
			get
			{
				return this.GetTable<SEMAINE>();
			}
		}
		
		public System.Data.Linq.Table<TYPE_HEB> TYPE_HEB
		{
			get
			{
				return this.GetTable<TYPE_HEB>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.COMPTE")]
	public partial class COMPTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CDUSER;
		
		private string _MDP;
		
		private string _NOMCPTE;
		
		private string _PRENOMCPTE;
		
		private System.Nullable<System.DateTime> _DATEINSCRIP;
		
		private System.Nullable<System.DateTime> _DATEFERME;
		
		private string _TYPECOMPTE;
		
		private string _ADRMAILCPTE;
		
		private string _NOTELCPTE;
		
		private string _NOPORTCPTE;
		
		private EntitySet<RESA> _RESA;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCDUSERChanging(string value);
    partial void OnCDUSERChanged();
    partial void OnMDPChanging(string value);
    partial void OnMDPChanged();
    partial void OnNOMCPTEChanging(string value);
    partial void OnNOMCPTEChanged();
    partial void OnPRENOMCPTEChanging(string value);
    partial void OnPRENOMCPTEChanged();
    partial void OnDATEINSCRIPChanging(System.Nullable<System.DateTime> value);
    partial void OnDATEINSCRIPChanged();
    partial void OnDATEFERMEChanging(System.Nullable<System.DateTime> value);
    partial void OnDATEFERMEChanged();
    partial void OnTYPECOMPTEChanging(string value);
    partial void OnTYPECOMPTEChanged();
    partial void OnADRMAILCPTEChanging(string value);
    partial void OnADRMAILCPTEChanged();
    partial void OnNOTELCPTEChanging(string value);
    partial void OnNOTELCPTEChanged();
    partial void OnNOPORTCPTEChanging(string value);
    partial void OnNOPORTCPTEChanged();
    #endregion
		
		public COMPTE()
		{
			this._RESA = new EntitySet<RESA>(new Action<RESA>(this.attach_RESA), new Action<RESA>(this.detach_RESA));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CDUSER", DbType="VarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CDUSER
		{
			get
			{
				return this._CDUSER;
			}
			set
			{
				if ((this._CDUSER != value))
				{
					this.OnCDUSERChanging(value);
					this.SendPropertyChanging();
					this._CDUSER = value;
					this.SendPropertyChanged("CDUSER");
					this.OnCDUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MDP", DbType="VarChar(128)")]
		public string MDP
		{
			get
			{
				return this._MDP;
			}
			set
			{
				if ((this._MDP != value))
				{
					this.OnMDPChanging(value);
					this.SendPropertyChanging();
					this._MDP = value;
					this.SendPropertyChanged("MDP");
					this.OnMDPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMCPTE", DbType="VarChar(128)")]
		public string NOMCPTE
		{
			get
			{
				return this._NOMCPTE;
			}
			set
			{
				if ((this._NOMCPTE != value))
				{
					this.OnNOMCPTEChanging(value);
					this.SendPropertyChanging();
					this._NOMCPTE = value;
					this.SendPropertyChanged("NOMCPTE");
					this.OnNOMCPTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRENOMCPTE", DbType="VarChar(128)")]
		public string PRENOMCPTE
		{
			get
			{
				return this._PRENOMCPTE;
			}
			set
			{
				if ((this._PRENOMCPTE != value))
				{
					this.OnPRENOMCPTEChanging(value);
					this.SendPropertyChanging();
					this._PRENOMCPTE = value;
					this.SendPropertyChanged("PRENOMCPTE");
					this.OnPRENOMCPTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATEINSCRIP", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATEINSCRIP
		{
			get
			{
				return this._DATEINSCRIP;
			}
			set
			{
				if ((this._DATEINSCRIP != value))
				{
					this.OnDATEINSCRIPChanging(value);
					this.SendPropertyChanging();
					this._DATEINSCRIP = value;
					this.SendPropertyChanged("DATEINSCRIP");
					this.OnDATEINSCRIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATEFERME", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATEFERME
		{
			get
			{
				return this._DATEFERME;
			}
			set
			{
				if ((this._DATEFERME != value))
				{
					this.OnDATEFERMEChanging(value);
					this.SendPropertyChanging();
					this._DATEFERME = value;
					this.SendPropertyChanged("DATEFERME");
					this.OnDATEFERMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPECOMPTE", DbType="VarChar(128)")]
		public string TYPECOMPTE
		{
			get
			{
				return this._TYPECOMPTE;
			}
			set
			{
				if ((this._TYPECOMPTE != value))
				{
					this.OnTYPECOMPTEChanging(value);
					this.SendPropertyChanging();
					this._TYPECOMPTE = value;
					this.SendPropertyChanged("TYPECOMPTE");
					this.OnTYPECOMPTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRMAILCPTE", DbType="VarChar(128)")]
		public string ADRMAILCPTE
		{
			get
			{
				return this._ADRMAILCPTE;
			}
			set
			{
				if ((this._ADRMAILCPTE != value))
				{
					this.OnADRMAILCPTEChanging(value);
					this.SendPropertyChanging();
					this._ADRMAILCPTE = value;
					this.SendPropertyChanged("ADRMAILCPTE");
					this.OnADRMAILCPTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTELCPTE", DbType="VarChar(128)")]
		public string NOTELCPTE
		{
			get
			{
				return this._NOTELCPTE;
			}
			set
			{
				if ((this._NOTELCPTE != value))
				{
					this.OnNOTELCPTEChanging(value);
					this.SendPropertyChanging();
					this._NOTELCPTE = value;
					this.SendPropertyChanged("NOTELCPTE");
					this.OnNOTELCPTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOPORTCPTE", DbType="VarChar(128)")]
		public string NOPORTCPTE
		{
			get
			{
				return this._NOPORTCPTE;
			}
			set
			{
				if ((this._NOPORTCPTE != value))
				{
					this.OnNOPORTCPTEChanging(value);
					this.SendPropertyChanging();
					this._NOPORTCPTE = value;
					this.SendPropertyChanged("NOPORTCPTE");
					this.OnNOPORTCPTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="COMPTE_RESA", Storage="_RESA", ThisKey="CDUSER", OtherKey="CDUSER")]
		public EntitySet<RESA> RESA
		{
			get
			{
				return this._RESA;
			}
			set
			{
				this._RESA.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RESA(RESA entity)
		{
			this.SendPropertyChanging();
			entity.COMPTE = this;
		}
		
		private void detach_RESA(RESA entity)
		{
			this.SendPropertyChanging();
			entity.COMPTE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ETAT_RESA")]
	public partial class ETAT_RESA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CODEETATRESA;
		
		private string _NOMETATRESA;
		
		private EntitySet<RESA> _RESA;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODEETATRESAChanging(string value);
    partial void OnCODEETATRESAChanged();
    partial void OnNOMETATRESAChanging(string value);
    partial void OnNOMETATRESAChanged();
    #endregion
		
		public ETAT_RESA()
		{
			this._RESA = new EntitySet<RESA>(new Action<RESA>(this.attach_RESA), new Action<RESA>(this.detach_RESA));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODEETATRESA", DbType="VarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CODEETATRESA
		{
			get
			{
				return this._CODEETATRESA;
			}
			set
			{
				if ((this._CODEETATRESA != value))
				{
					this.OnCODEETATRESAChanging(value);
					this.SendPropertyChanging();
					this._CODEETATRESA = value;
					this.SendPropertyChanged("CODEETATRESA");
					this.OnCODEETATRESAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMETATRESA", DbType="VarChar(128)")]
		public string NOMETATRESA
		{
			get
			{
				return this._NOMETATRESA;
			}
			set
			{
				if ((this._NOMETATRESA != value))
				{
					this.OnNOMETATRESAChanging(value);
					this.SendPropertyChanging();
					this._NOMETATRESA = value;
					this.SendPropertyChanged("NOMETATRESA");
					this.OnNOMETATRESAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ETAT_RESA_RESA", Storage="_RESA", ThisKey="CODEETATRESA", OtherKey="CODEETATRESA")]
		public EntitySet<RESA> RESA
		{
			get
			{
				return this._RESA;
			}
			set
			{
				this._RESA.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RESA(RESA entity)
		{
			this.SendPropertyChanging();
			entity.ETAT_RESA = this;
		}
		
		private void detach_RESA(RESA entity)
		{
			this.SendPropertyChanging();
			entity.ETAT_RESA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HEBERGEMENT")]
	public partial class HEBERGEMENT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NOHEB;
		
		private string _CODETYPEHEB;
		
		private string _NOMHEB;
		
		private System.Nullable<int> _NBPLACEHEB;
		
		private System.Nullable<int> _SURFACEHEB;
		
		private System.Nullable<bool> _INTERNET;
		
		private System.Nullable<int> _ANNEEHEB;
		
		private string _SECTEURHEB;
		
		private string _ORIENTATIONHEB;
		
		private string _ETATHEB;
		
		private string _DESCRIHEB;
		
		private string _PHOTOHEB;
		
		private System.Nullable<decimal> _TARIFSEMHEB;
		
		private EntitySet<RESA> _RESA;
		
		private EntityRef<TYPE_HEB> _TYPE_HEB;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNOHEBChanging(int value);
    partial void OnNOHEBChanged();
    partial void OnCODETYPEHEBChanging(string value);
    partial void OnCODETYPEHEBChanged();
    partial void OnNOMHEBChanging(string value);
    partial void OnNOMHEBChanged();
    partial void OnNBPLACEHEBChanging(System.Nullable<int> value);
    partial void OnNBPLACEHEBChanged();
    partial void OnSURFACEHEBChanging(System.Nullable<int> value);
    partial void OnSURFACEHEBChanged();
    partial void OnINTERNETChanging(System.Nullable<bool> value);
    partial void OnINTERNETChanged();
    partial void OnANNEEHEBChanging(System.Nullable<int> value);
    partial void OnANNEEHEBChanged();
    partial void OnSECTEURHEBChanging(string value);
    partial void OnSECTEURHEBChanged();
    partial void OnORIENTATIONHEBChanging(string value);
    partial void OnORIENTATIONHEBChanged();
    partial void OnETATHEBChanging(string value);
    partial void OnETATHEBChanged();
    partial void OnDESCRIHEBChanging(string value);
    partial void OnDESCRIHEBChanged();
    partial void OnPHOTOHEBChanging(string value);
    partial void OnPHOTOHEBChanged();
    partial void OnTARIFSEMHEBChanging(System.Nullable<decimal> value);
    partial void OnTARIFSEMHEBChanged();
    #endregion
		
		public HEBERGEMENT()
		{
			this._RESA = new EntitySet<RESA>(new Action<RESA>(this.attach_RESA), new Action<RESA>(this.detach_RESA));
			this._TYPE_HEB = default(EntityRef<TYPE_HEB>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOHEB", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int NOHEB
		{
			get
			{
				return this._NOHEB;
			}
			set
			{
				if ((this._NOHEB != value))
				{
					this.OnNOHEBChanging(value);
					this.SendPropertyChanging();
					this._NOHEB = value;
					this.SendPropertyChanged("NOHEB");
					this.OnNOHEBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODETYPEHEB", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string CODETYPEHEB
		{
			get
			{
				return this._CODETYPEHEB;
			}
			set
			{
				if ((this._CODETYPEHEB != value))
				{
					if (this._TYPE_HEB.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCODETYPEHEBChanging(value);
					this.SendPropertyChanging();
					this._CODETYPEHEB = value;
					this.SendPropertyChanged("CODETYPEHEB");
					this.OnCODETYPEHEBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMHEB", DbType="VarChar(128)")]
		public string NOMHEB
		{
			get
			{
				return this._NOMHEB;
			}
			set
			{
				if ((this._NOMHEB != value))
				{
					this.OnNOMHEBChanging(value);
					this.SendPropertyChanging();
					this._NOMHEB = value;
					this.SendPropertyChanged("NOMHEB");
					this.OnNOMHEBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NBPLACEHEB", DbType="Int")]
		public System.Nullable<int> NBPLACEHEB
		{
			get
			{
				return this._NBPLACEHEB;
			}
			set
			{
				if ((this._NBPLACEHEB != value))
				{
					this.OnNBPLACEHEBChanging(value);
					this.SendPropertyChanging();
					this._NBPLACEHEB = value;
					this.SendPropertyChanged("NBPLACEHEB");
					this.OnNBPLACEHEBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SURFACEHEB", DbType="Int")]
		public System.Nullable<int> SURFACEHEB
		{
			get
			{
				return this._SURFACEHEB;
			}
			set
			{
				if ((this._SURFACEHEB != value))
				{
					this.OnSURFACEHEBChanging(value);
					this.SendPropertyChanging();
					this._SURFACEHEB = value;
					this.SendPropertyChanged("SURFACEHEB");
					this.OnSURFACEHEBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTERNET", DbType="Bit")]
		public System.Nullable<bool> INTERNET
		{
			get
			{
				return this._INTERNET;
			}
			set
			{
				if ((this._INTERNET != value))
				{
					this.OnINTERNETChanging(value);
					this.SendPropertyChanging();
					this._INTERNET = value;
					this.SendPropertyChanged("INTERNET");
					this.OnINTERNETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANNEEHEB", DbType="Int")]
		public System.Nullable<int> ANNEEHEB
		{
			get
			{
				return this._ANNEEHEB;
			}
			set
			{
				if ((this._ANNEEHEB != value))
				{
					this.OnANNEEHEBChanging(value);
					this.SendPropertyChanging();
					this._ANNEEHEB = value;
					this.SendPropertyChanged("ANNEEHEB");
					this.OnANNEEHEBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECTEURHEB", DbType="VarChar(128)")]
		public string SECTEURHEB
		{
			get
			{
				return this._SECTEURHEB;
			}
			set
			{
				if ((this._SECTEURHEB != value))
				{
					this.OnSECTEURHEBChanging(value);
					this.SendPropertyChanging();
					this._SECTEURHEB = value;
					this.SendPropertyChanged("SECTEURHEB");
					this.OnSECTEURHEBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORIENTATIONHEB", DbType="VarChar(128)")]
		public string ORIENTATIONHEB
		{
			get
			{
				return this._ORIENTATIONHEB;
			}
			set
			{
				if ((this._ORIENTATIONHEB != value))
				{
					this.OnORIENTATIONHEBChanging(value);
					this.SendPropertyChanging();
					this._ORIENTATIONHEB = value;
					this.SendPropertyChanged("ORIENTATIONHEB");
					this.OnORIENTATIONHEBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ETATHEB", DbType="VarChar(128)")]
		public string ETATHEB
		{
			get
			{
				return this._ETATHEB;
			}
			set
			{
				if ((this._ETATHEB != value))
				{
					this.OnETATHEBChanging(value);
					this.SendPropertyChanging();
					this._ETATHEB = value;
					this.SendPropertyChanged("ETATHEB");
					this.OnETATHEBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIHEB", DbType="VarChar(128)")]
		public string DESCRIHEB
		{
			get
			{
				return this._DESCRIHEB;
			}
			set
			{
				if ((this._DESCRIHEB != value))
				{
					this.OnDESCRIHEBChanging(value);
					this.SendPropertyChanging();
					this._DESCRIHEB = value;
					this.SendPropertyChanged("DESCRIHEB");
					this.OnDESCRIHEBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHOTOHEB", DbType="VarChar(128)")]
		public string PHOTOHEB
		{
			get
			{
				return this._PHOTOHEB;
			}
			set
			{
				if ((this._PHOTOHEB != value))
				{
					this.OnPHOTOHEBChanging(value);
					this.SendPropertyChanging();
					this._PHOTOHEB = value;
					this.SendPropertyChanged("PHOTOHEB");
					this.OnPHOTOHEBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARIFSEMHEB", DbType="Money")]
		public System.Nullable<decimal> TARIFSEMHEB
		{
			get
			{
				return this._TARIFSEMHEB;
			}
			set
			{
				if ((this._TARIFSEMHEB != value))
				{
					this.OnTARIFSEMHEBChanging(value);
					this.SendPropertyChanging();
					this._TARIFSEMHEB = value;
					this.SendPropertyChanged("TARIFSEMHEB");
					this.OnTARIFSEMHEBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HEBERGEMENT_RESA", Storage="_RESA", ThisKey="NOHEB", OtherKey="NOHEB")]
		public EntitySet<RESA> RESA
		{
			get
			{
				return this._RESA;
			}
			set
			{
				this._RESA.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TYPE_HEB_HEBERGEMENT", Storage="_TYPE_HEB", ThisKey="CODETYPEHEB", OtherKey="CODETYPEHEB", IsForeignKey=true)]
		public TYPE_HEB TYPE_HEB
		{
			get
			{
				return this._TYPE_HEB.Entity;
			}
			set
			{
				TYPE_HEB previousValue = this._TYPE_HEB.Entity;
				if (((previousValue != value) 
							|| (this._TYPE_HEB.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TYPE_HEB.Entity = null;
						previousValue.HEBERGEMENT.Remove(this);
					}
					this._TYPE_HEB.Entity = value;
					if ((value != null))
					{
						value.HEBERGEMENT.Add(this);
						this._CODETYPEHEB = value.CODETYPEHEB;
					}
					else
					{
						this._CODETYPEHEB = default(string);
					}
					this.SendPropertyChanged("TYPE_HEB");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RESA(RESA entity)
		{
			this.SendPropertyChanging();
			entity.HEBERGEMENT = this;
		}
		
		private void detach_RESA(RESA entity)
		{
			this.SendPropertyChanging();
			entity.HEBERGEMENT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RESA")]
	public partial class RESA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NORESA;
		
		private string _CDUSER;
		
		private System.DateTime _DATEDEBSEM;
		
		private int _NOHEB;
		
		private string _CODEETATRESA;
		
		private System.Nullable<System.DateTime> _DATERESA;
		
		private System.Nullable<System.DateTime> _DATEARRHES;
		
		private System.Nullable<decimal> _MONTANTARRHES;
		
		private System.Nullable<int> _NBOCCUPANT;
		
		private System.Nullable<decimal> _TARIFSEMRESA;
		
		private EntityRef<COMPTE> _COMPTE;
		
		private EntityRef<ETAT_RESA> _ETAT_RESA;
		
		private EntityRef<HEBERGEMENT> _HEBERGEMENT;
		
		private EntityRef<SEMAINE> _SEMAINE;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNORESAChanging(int value);
    partial void OnNORESAChanged();
    partial void OnCDUSERChanging(string value);
    partial void OnCDUSERChanged();
    partial void OnDATEDEBSEMChanging(System.DateTime value);
    partial void OnDATEDEBSEMChanged();
    partial void OnNOHEBChanging(int value);
    partial void OnNOHEBChanged();
    partial void OnCODEETATRESAChanging(string value);
    partial void OnCODEETATRESAChanged();
    partial void OnDATERESAChanging(System.Nullable<System.DateTime> value);
    partial void OnDATERESAChanged();
    partial void OnDATEARRHESChanging(System.Nullable<System.DateTime> value);
    partial void OnDATEARRHESChanged();
    partial void OnMONTANTARRHESChanging(System.Nullable<decimal> value);
    partial void OnMONTANTARRHESChanged();
    partial void OnNBOCCUPANTChanging(System.Nullable<int> value);
    partial void OnNBOCCUPANTChanged();
    partial void OnTARIFSEMRESAChanging(System.Nullable<decimal> value);
    partial void OnTARIFSEMRESAChanged();
    #endregion
		
		public RESA()
		{
			this._COMPTE = default(EntityRef<COMPTE>);
			this._ETAT_RESA = default(EntityRef<ETAT_RESA>);
			this._HEBERGEMENT = default(EntityRef<HEBERGEMENT>);
			this._SEMAINE = default(EntityRef<SEMAINE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NORESA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int NORESA
		{
			get
			{
				return this._NORESA;
			}
			set
			{
				if ((this._NORESA != value))
				{
					this.OnNORESAChanging(value);
					this.SendPropertyChanging();
					this._NORESA = value;
					this.SendPropertyChanged("NORESA");
					this.OnNORESAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CDUSER", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string CDUSER
		{
			get
			{
				return this._CDUSER;
			}
			set
			{
				if ((this._CDUSER != value))
				{
					if (this._COMPTE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCDUSERChanging(value);
					this.SendPropertyChanging();
					this._CDUSER = value;
					this.SendPropertyChanged("CDUSER");
					this.OnCDUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATEDEBSEM", DbType="DateTime NOT NULL")]
		public System.DateTime DATEDEBSEM
		{
			get
			{
				return this._DATEDEBSEM;
			}
			set
			{
				if ((this._DATEDEBSEM != value))
				{
					if (this._SEMAINE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDATEDEBSEMChanging(value);
					this.SendPropertyChanging();
					this._DATEDEBSEM = value;
					this.SendPropertyChanged("DATEDEBSEM");
					this.OnDATEDEBSEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOHEB", DbType="Int NOT NULL")]
		public int NOHEB
		{
			get
			{
				return this._NOHEB;
			}
			set
			{
				if ((this._NOHEB != value))
				{
					if (this._HEBERGEMENT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNOHEBChanging(value);
					this.SendPropertyChanging();
					this._NOHEB = value;
					this.SendPropertyChanged("NOHEB");
					this.OnNOHEBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODEETATRESA", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string CODEETATRESA
		{
			get
			{
				return this._CODEETATRESA;
			}
			set
			{
				if ((this._CODEETATRESA != value))
				{
					if (this._ETAT_RESA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCODEETATRESAChanging(value);
					this.SendPropertyChanging();
					this._CODEETATRESA = value;
					this.SendPropertyChanged("CODEETATRESA");
					this.OnCODEETATRESAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATERESA", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATERESA
		{
			get
			{
				return this._DATERESA;
			}
			set
			{
				if ((this._DATERESA != value))
				{
					this.OnDATERESAChanging(value);
					this.SendPropertyChanging();
					this._DATERESA = value;
					this.SendPropertyChanged("DATERESA");
					this.OnDATERESAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATEARRHES", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATEARRHES
		{
			get
			{
				return this._DATEARRHES;
			}
			set
			{
				if ((this._DATEARRHES != value))
				{
					this.OnDATEARRHESChanging(value);
					this.SendPropertyChanging();
					this._DATEARRHES = value;
					this.SendPropertyChanged("DATEARRHES");
					this.OnDATEARRHESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONTANTARRHES", DbType="Money")]
		public System.Nullable<decimal> MONTANTARRHES
		{
			get
			{
				return this._MONTANTARRHES;
			}
			set
			{
				if ((this._MONTANTARRHES != value))
				{
					this.OnMONTANTARRHESChanging(value);
					this.SendPropertyChanging();
					this._MONTANTARRHES = value;
					this.SendPropertyChanged("MONTANTARRHES");
					this.OnMONTANTARRHESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NBOCCUPANT", DbType="Int")]
		public System.Nullable<int> NBOCCUPANT
		{
			get
			{
				return this._NBOCCUPANT;
			}
			set
			{
				if ((this._NBOCCUPANT != value))
				{
					this.OnNBOCCUPANTChanging(value);
					this.SendPropertyChanging();
					this._NBOCCUPANT = value;
					this.SendPropertyChanged("NBOCCUPANT");
					this.OnNBOCCUPANTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARIFSEMRESA", DbType="Money")]
		public System.Nullable<decimal> TARIFSEMRESA
		{
			get
			{
				return this._TARIFSEMRESA;
			}
			set
			{
				if ((this._TARIFSEMRESA != value))
				{
					this.OnTARIFSEMRESAChanging(value);
					this.SendPropertyChanging();
					this._TARIFSEMRESA = value;
					this.SendPropertyChanged("TARIFSEMRESA");
					this.OnTARIFSEMRESAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="COMPTE_RESA", Storage="_COMPTE", ThisKey="CDUSER", OtherKey="CDUSER", IsForeignKey=true)]
		public COMPTE COMPTE
		{
			get
			{
				return this._COMPTE.Entity;
			}
			set
			{
				COMPTE previousValue = this._COMPTE.Entity;
				if (((previousValue != value) 
							|| (this._COMPTE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._COMPTE.Entity = null;
						previousValue.RESA.Remove(this);
					}
					this._COMPTE.Entity = value;
					if ((value != null))
					{
						value.RESA.Add(this);
						this._CDUSER = value.CDUSER;
					}
					else
					{
						this._CDUSER = default(string);
					}
					this.SendPropertyChanged("COMPTE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ETAT_RESA_RESA", Storage="_ETAT_RESA", ThisKey="CODEETATRESA", OtherKey="CODEETATRESA", IsForeignKey=true)]
		public ETAT_RESA ETAT_RESA
		{
			get
			{
				return this._ETAT_RESA.Entity;
			}
			set
			{
				ETAT_RESA previousValue = this._ETAT_RESA.Entity;
				if (((previousValue != value) 
							|| (this._ETAT_RESA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ETAT_RESA.Entity = null;
						previousValue.RESA.Remove(this);
					}
					this._ETAT_RESA.Entity = value;
					if ((value != null))
					{
						value.RESA.Add(this);
						this._CODEETATRESA = value.CODEETATRESA;
					}
					else
					{
						this._CODEETATRESA = default(string);
					}
					this.SendPropertyChanged("ETAT_RESA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HEBERGEMENT_RESA", Storage="_HEBERGEMENT", ThisKey="NOHEB", OtherKey="NOHEB", IsForeignKey=true)]
		public HEBERGEMENT HEBERGEMENT
		{
			get
			{
				return this._HEBERGEMENT.Entity;
			}
			set
			{
				HEBERGEMENT previousValue = this._HEBERGEMENT.Entity;
				if (((previousValue != value) 
							|| (this._HEBERGEMENT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HEBERGEMENT.Entity = null;
						previousValue.RESA.Remove(this);
					}
					this._HEBERGEMENT.Entity = value;
					if ((value != null))
					{
						value.RESA.Add(this);
						this._NOHEB = value.NOHEB;
					}
					else
					{
						this._NOHEB = default(int);
					}
					this.SendPropertyChanged("HEBERGEMENT");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SEMAINE_RESA", Storage="_SEMAINE", ThisKey="DATEDEBSEM", OtherKey="DATEDEBSEM", IsForeignKey=true)]
		public SEMAINE SEMAINE
		{
			get
			{
				return this._SEMAINE.Entity;
			}
			set
			{
				SEMAINE previousValue = this._SEMAINE.Entity;
				if (((previousValue != value) 
							|| (this._SEMAINE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SEMAINE.Entity = null;
						previousValue.RESA.Remove(this);
					}
					this._SEMAINE.Entity = value;
					if ((value != null))
					{
						value.RESA.Add(this);
						this._DATEDEBSEM = value.DATEDEBSEM;
					}
					else
					{
						this._DATEDEBSEM = default(System.DateTime);
					}
					this.SendPropertyChanged("SEMAINE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SEMAINE")]
	public partial class SEMAINE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _DATEDEBSEM;
		
		private System.Nullable<System.DateTime> _DATEFINSEM;
		
		private EntitySet<RESA> _RESA;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDATEDEBSEMChanging(System.DateTime value);
    partial void OnDATEDEBSEMChanged();
    partial void OnDATEFINSEMChanging(System.Nullable<System.DateTime> value);
    partial void OnDATEFINSEMChanged();
    #endregion
		
		public SEMAINE()
		{
			this._RESA = new EntitySet<RESA>(new Action<RESA>(this.attach_RESA), new Action<RESA>(this.detach_RESA));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATEDEBSEM", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime DATEDEBSEM
		{
			get
			{
				return this._DATEDEBSEM;
			}
			set
			{
				if ((this._DATEDEBSEM != value))
				{
					this.OnDATEDEBSEMChanging(value);
					this.SendPropertyChanging();
					this._DATEDEBSEM = value;
					this.SendPropertyChanged("DATEDEBSEM");
					this.OnDATEDEBSEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATEFINSEM", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATEFINSEM
		{
			get
			{
				return this._DATEFINSEM;
			}
			set
			{
				if ((this._DATEFINSEM != value))
				{
					this.OnDATEFINSEMChanging(value);
					this.SendPropertyChanging();
					this._DATEFINSEM = value;
					this.SendPropertyChanged("DATEFINSEM");
					this.OnDATEFINSEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SEMAINE_RESA", Storage="_RESA", ThisKey="DATEDEBSEM", OtherKey="DATEDEBSEM")]
		public EntitySet<RESA> RESA
		{
			get
			{
				return this._RESA;
			}
			set
			{
				this._RESA.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RESA(RESA entity)
		{
			this.SendPropertyChanging();
			entity.SEMAINE = this;
		}
		
		private void detach_RESA(RESA entity)
		{
			this.SendPropertyChanging();
			entity.SEMAINE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TYPE_HEB")]
	public partial class TYPE_HEB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CODETYPEHEB;
		
		private string _NOMTYPEHEB;
		
		private EntitySet<HEBERGEMENT> _HEBERGEMENT;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODETYPEHEBChanging(string value);
    partial void OnCODETYPEHEBChanged();
    partial void OnNOMTYPEHEBChanging(string value);
    partial void OnNOMTYPEHEBChanged();
    #endregion
		
		public TYPE_HEB()
		{
			this._HEBERGEMENT = new EntitySet<HEBERGEMENT>(new Action<HEBERGEMENT>(this.attach_HEBERGEMENT), new Action<HEBERGEMENT>(this.detach_HEBERGEMENT));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODETYPEHEB", DbType="VarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CODETYPEHEB
		{
			get
			{
				return this._CODETYPEHEB;
			}
			set
			{
				if ((this._CODETYPEHEB != value))
				{
					this.OnCODETYPEHEBChanging(value);
					this.SendPropertyChanging();
					this._CODETYPEHEB = value;
					this.SendPropertyChanged("CODETYPEHEB");
					this.OnCODETYPEHEBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMTYPEHEB", DbType="VarChar(128)")]
		public string NOMTYPEHEB
		{
			get
			{
				return this._NOMTYPEHEB;
			}
			set
			{
				if ((this._NOMTYPEHEB != value))
				{
					this.OnNOMTYPEHEBChanging(value);
					this.SendPropertyChanging();
					this._NOMTYPEHEB = value;
					this.SendPropertyChanged("NOMTYPEHEB");
					this.OnNOMTYPEHEBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TYPE_HEB_HEBERGEMENT", Storage="_HEBERGEMENT", ThisKey="CODETYPEHEB", OtherKey="CODETYPEHEB")]
		public EntitySet<HEBERGEMENT> HEBERGEMENT
		{
			get
			{
				return this._HEBERGEMENT;
			}
			set
			{
				this._HEBERGEMENT.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HEBERGEMENT(HEBERGEMENT entity)
		{
			this.SendPropertyChanging();
			entity.TYPE_HEB = this;
		}
		
		private void detach_HEBERGEMENT(HEBERGEMENT entity)
		{
			this.SendPropertyChanging();
			entity.TYPE_HEB = null;
		}
	}
}
#pragma warning restore 1591
